//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerProjectConfigs = new HashSet<CustomerProjectConfig>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public string Name { get; set; }
        public string Work_Function { get; set; }
        public string Phone { get; set; }
        public string AlternatePhone { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public Nullable<decimal> EstimatedSale { get; set; }
        public Nullable<System.DateTime> LastContact_Dt { get; set; }
        public Nullable<System.DateTime> NextAction_Dt { get; set; }
        public string LeadSource { get; set; }
        public Nullable<int> LeadStatus { get; set; }
        public string Conv_Cust_Status { get; set; }
        public string Comments { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProjectConfig> CustomerProjectConfigs { get; set; }
        public virtual leadStatus_Master leadStatus_Master { get; set; }
        public virtual User_Master User_Master { get; set; }
        public virtual Project Project { get; set; }
    }
}
