//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerProjectConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerProjectConfig()
        {
            this.ProjectInstanceConfigs = new HashSet<ProjectInstanceConfig>();
        }
    
        public System.Guid Id { get; set; }
        [Required]
        public string ProjectName { get; set; }

        [Display(Name = "Choose a Customer")]
        public Nullable<System.Guid> CustomerID { get; set; }

        [Display(Name = "Choose a Consultant")]
        public Nullable<System.Guid> ConsultantID { get; set; }
        public System.DateTime LastUpdated_Dt { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInstanceConfig> ProjectInstanceConfigs { get; set; }
        public virtual Consultant Consultant { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
