//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPInput_SimplificationReport
    {
        public int S_No { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Relevance { get; set; }
        public string LoB_Technology { get; set; }
        public string Business_Area { get; set; }
        public string Consistency_Status { get; set; }
        public string Manual_Status { get; set; }
        public string SAP_Notes { get; set; }
        public string Relevance_Summary { get; set; }
    }
}
