//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPInput_CustomCode
    {
        public int S_No { get; set; }
        public string Custom_Code_Topic { get; set; }
        public string Status { get; set; }
        public string Application_Component { get; set; }
        public string Custom_Code_Note { get; set; }
    }
}
