//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Work_Function { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> EstimatedSale { get; set; }
        public Nullable<System.DateTime> LastContact_Dt { get; set; }
        public Nullable<System.DateTime> NextAction_Dt { get; set; }
        public Nullable<System.DateTime> NextContact_Dt { get; set; }
        public string LeadStatus { get; set; }
        public string LeadSource { get; set; }
        public string Conv_Cust_Status { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User_Master User_Master { get; set; }
        public virtual Project Project { get; set; }
    }
}
