//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAcc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProAccEntities1 : DbContext
    {
        public ProAccEntities1()
            : base("name=ProAccEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Milestone> Milestones { get; set; }
        public virtual DbSet<MilestoneDetail> MilestoneDetails { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
        public virtual DbSet<SAPInput_Activities> SAPInput_Activities { get; set; }
        public virtual DbSet<SAPInput_SimplificationReport> SAPInput_SimplificationReport { get; set; }
        public virtual DbSet<StageStatu> StageStatus { get; set; }
        public virtual DbSet<SubMilestoneConfig> SubMilestoneConfigs { get; set; }
        public virtual DbSet<User_Master> User_Master { get; set; }
    
        public virtual ObjectResult<SP_ReadinessReport_Result> SP_ReadinessReport(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReadinessReport_Result>("SP_ReadinessReport", typeParameter);
        }
    
        public virtual ObjectResult<string> SP_SimplificationReport(string type, string input)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SimplificationReport", typeParameter, inputParameter);
        }
    }
}
