//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Proj_ID { get; set; }
        public Nullable<System.Guid> SubMile_ID { get; set; }
        public int OrderNum { get; set; }
        public Nullable<int> StatgeStatus_ID { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> Info_Dt { get; set; }
        public System.DateTime LastUpdated_Dt { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual SubMilestoneConfig SubMilestoneConfig { get; set; }
        public virtual StageStatu StageStatu { get; set; }
    }
}
