//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPInput_Activities
    {
        public double S_No { get; set; }
        public string Related_Simplification_Items { get; set; }
        public string Activities { get; set; }
        public string Phase { get; set; }
        public string Condition { get; set; }
        public string Additional_Information { get; set; }
    }
}
