//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMilestoneConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMilestoneConfig()
        {
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MilestoneDetails_ID { get; set; }
        public string SubMilestoneName { get; set; }
        public int SubMail_Order { get; set; }
        public string ProjectSpec { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MilestoneDetail MilestoneDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
